### ISSUE TITLE
Crash When End Dragon Dies

### ISSUE THREAD

**Issue by PiccoTerra** [minecraftabnormals/The-Endergetic-Expansion#214] opened 2022-05-28 15:42 UTC
I am playing on a rather modded game and supposedly the crash is with your mod? Anything I can do?
[crash-2022-05-28_14.47.54-server.txt](https://github.com/team-abnormals/endergetic/files/8791401/crash-2022-05-28_14.47.54-server.txt)
[crash-2022-05-28_17.08.43-server.txt](https://github.com/team-abnormals/endergetic/files/8791402/crash-2022-05-28_17.08.43-server.txt)
[crash-2022-05-28_17.14.46-server.txt](https://github.com/team-abnormals/endergetic/files/8791403/crash-2022-05-28_17.14.46-server.txt)
[crash-2022-05-25_19.05.22-fml.txt](https://github.com/team-abnormals/endergetic/files/8791404/crash-2022-05-25_19.05.22-fml.txt)

**Comment by SmellyModder** [comment] 2022-05-29 13:14
Duplicate of #211.
This issue is fixed in the latest version of Endergetic: https://www.curseforge.com/minecraft/mc-mods/endergetic/files/3750371

**Closed as completed by SmellyModder** 2022-05-29 13:14 UTC
