### ISSUE TITLE
Game Crashing after Ender Dragon Killed

### ISSUE THREAD

**Issue by Formula-44** [minecraftabnormals/The-Endergetic-Expansion#212] opened 2022-04-13 15:53 UTC
After the dragon is killed, the portal fails to open and immediately crashes the game. The Launcher gives this message: 
The game crashed whilst ticking entity
Error: net.minecraftforge.fml.common.ObfuscationReflectionHelper$UnableToFindFieldException: java.lang.NoSuchFieldException: gateways
Exit Code: -1
Relaunching the game and opening the world again results in the same issue.
I am in 1.16.5 Forge

**Comment by SmellyModder** [comment] 2022-04-13 18:15
Duplicate of #211

**Closed as completed by SmellyModder** 2022-04-13 18:15 UTC
